language: java

services:
  - postgresql

before_script:
  - psql -c 'create database travisdb;' -U postgres

before_install:
 - chmod +x gradlew

env:
  - DATABASE_URL="postgres://postgres:@localhost:5432/travisdb"
