language: java

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - psql -c "CREATE ROLE foo SUPERUSER PASSWORD 'bar';" -U postgres

before_install:
  - chmod +x gradlew

env:
  - DATABASE_URL="postgres://foo:bar@localhost:5432/travisdb"

script:
  - ./gradlew build --stacktrace --info --debug --scan
  - ./gradlew check jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
