language: java

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres

before_install:
  - chmod +x gradlew

script:
  - ./gradlew assemble -s

env:
  - DATABASE_URL="postgres://foo:bar@localhost:5432/travisdb"
